# Generated by Django 5.2.9 on 2025-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('qr_image', models.ImageField(upload_to='qrcodes/')),
            ],
        ),
    ]
